import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import ReactPDF from '@react-pdf/renderer';

// Define styles for the PDF
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '2 solid #2563eb',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    color: '#2563eb',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 3,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: 10,
    backgroundColor: '#f3f4f6',
    padding: 8,
  },
  text: {
    fontSize: 11,
    color: '#374151',
    lineHeight: 1.6,
    marginBottom: 10,
  },
  tags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
    marginTop: 10,
  },
  tag: {
    backgroundColor: '#fed7aa',
    color: '#9a3412',
    padding: '4 8',
    borderRadius: 12,
    fontSize: 9,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 9,
    color: '#9ca3af',
    textAlign: 'center',
    borderTop: '1 solid #e5e7eb',
    paddingTop: 10,
  },
});

interface FeedbackPDFProps {
  essayText: string;
  feedbackText: string;
  essayType: string;
  characterCount: number;
  qualityTags: string[];
  date: string;
}

// React PDF Document component
const FeedbackPDF = ({
  essayText,
  feedbackText,
  essayType,
  characterCount,
  qualityTags,
  date,
}: FeedbackPDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>Medical School HQ</Text>
        <Text style={styles.subtitle}>Personal Statement Feedback</Text>
        <Text style={styles.subtitle}>
          {essayType} • {characterCount} characters • {date}
        </Text>
      </View>

      {/* Original Essay Section */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Your Personal Statement</Text>
        <Text style={styles.text}>{essayText}</Text>
      </View>

      {/* Feedback Section */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>AI Feedback</Text>
        <Text style={styles.text}>{feedbackText}</Text>
      </View>

      {/* Quality Tags */}
      {qualityTags && qualityTags.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Key Areas Addressed</Text>
          <View style={styles.tags}>
            {qualityTags.map((tag, index) => (
              <Text key={index} style={styles.tag}>
                {tag}
              </Text>
            ))}
          </View>
        </View>
      )}

      {/* Footer */}
      <View style={styles.footer}>
        <Text>
          Generated by Medical School HQ • This feedback is AI-generated and
          should be used as guidance
        </Text>
      </View>
    </Page>
  </Document>
);

/**
 * Generate PDF buffer from feedback data
 */
export async function generateFeedbackPDF(
  data: FeedbackPDFProps
): Promise<Buffer> {
  const pdfDoc = <FeedbackPDF {...data} />;
  const pdfBuffer = await ReactPDF.renderToBuffer(pdfDoc);
  return pdfBuffer;
}
